// Quelle: Wikidata
export const LOCATIONS = [
  // Deutsche Bundesländer
  "Baden-Württemberg",
  "Bayern",
  "Berlin",
  "Brandenburg",
  "Bremen",
  "Hamburg",
  "Hessen",
  "Mecklenburg-Vorpommern",
  "Niedersachsen",
  "Nordrhein-Westfalen",
  "Rheinland-Pfalz",
  "Saarland",
  "Sachsen",
  "Sachsen-Anhalt",
  "Schleswig-Holstein",
  "Thüringen",

  // Deutsche Großstädte (Quelle: Wikidata)
  "Aachen",
  "Aalen",
  "Ahaus",
  "Ahlen",
  "Ahrensburg",
  "Albstadt",
  "Alsdorf",
  "Altenburg",
  "Amberg",
  "Andernach",
  "Ansbach",
  "Arnsberg",
  "Aschaffenburg",
  "Augsburg",
  "Aurich",
  "Backnang",
  "Bad Godesberg",
  "Bad Hersfeld",
  "Bad Homburg vor der Höhe",
  "Bad Kreuznach",
  "Bad Nauheim",
  "Bad Oeynhausen",
  "Bad Salzuflen",
  "Bad Vilbel",
  "Baden-Baden",
  "Balingen",
  "Bamberg",
  "Barsinghausen",
  "Bautzen",
  "Bayreuth",
  "Beckum",
  "Bensheim",
  "Bergheim",
  "Bergisch Gladbach",
  "Bergkamen",
  "Bernau bei Berlin",
  "Bernburg",
  "Beuel",
  "Biberach an der Riß",
  "Bielefeld",
  "Bietigheim-Bissingen",
  "Bitterfeld-Wolfen",
  "Bocholt",
  "Bochum",
  "Bonn",
  "Borken",
  "Bornheim",
  "Bottrop",
  "Bramsche",
  "Brandenburg an der Havel",
  "Braunschweig",
  "Bremerhaven",
  "Bretten",
  "Bruchsal",
  "Brühl",
  "Buchholz in der Nordheide",
  "Burgdorf",
  "Buxtehude",
  "Böblingen",
  "Bünde",
  "Castrop-Rauxel",
  "Celle",
  "Chemnitz",
  "Cloppenburg",
  "Coburg",
  "Coesfeld",
  "Cottbus",
  "Crailsheim",
  "Cuxhaven",
  "Dachau",
  "Darmstadt",
  "Datteln",
  "Deggendorf",
  "Delbrück",
  "Delmenhorst",
  "Dessau-Roßlau",
  "Detmold",
  "Dietzenbach",
  "Dinslaken",
  "Dormagen",
  "Dorsten",
  "Dortmund",
  "Dreieich",
  "Dresden",
  "Duisburg",
  "Dülmen",
  "Düren",
  "Düsseldorf",
  "Einbeck",
  "Eisenach",
  "Elmshorn",
  "Emden",
  "Emmerich am Rhein",
  "Emsdetten",
  "Ennepetal",
  "Erding",
  "Erfurt",
  "Erftstadt",
  "Erkelenz",
  "Erkrath",
  "Erlangen",
  "Eschweiler",
  "Essen",
  "Esslingen am Neckar",
  "Ettlingen",
  "Euskirchen",
  "Falkensee",
  "Fellbach",
  "Filderstadt",
  "Flensburg",
  "Forchheim",
  "Frankenthal",
  "Frankfurt am Main",
  "Frankfurt (Oder)",
  "Frechen",
  "Freiberg",
  "Freiburg im Breisgau",
  "Freising",
  "Freital",
  "Friedberg",
  "Friedrichshafen",
  "Fulda",
  "Fürstenfeldbruck",
  "Fürstenwalde",
  "Fürth",
  "Gaggenau",
  "Garbsen",
  "Geesthacht",
  "Geestland",
  "Geldern",
  "Gelsenkirchen",
  "Gera",
  "Germering",
  "Gevelsberg",
  "Gießen",
  "Gifhorn",
  "Gladbeck",
  "Goch",
  "Goslar",
  "Gotha",
  "Grevenbroich",
  "Greven",
  "Greifswald",
  "Gronau",
  "Gummersbach",
  "Gütersloh",
  "Göppingen",
  "Görlitz",
  "Göttingen",
  "Haan",
  "Hagen",
  "Halberstadt",
  "Halle (Saale)",
  "Halle-Neustadt",
  "Haltern am See",
  "Hameln",
  "Hamm",
  "Hanau",
  "Hannover",
  "Hattingen",
  "Heidelberg",
  "Heidenheim an der Brenz",
  "Heilbronn",
  "Heinsberg",
  "Hemer",
  "Hennef",
  "Herford",
  "Herne",
  "Herrenberg",
  "Herten",
  "Herzogenrath",
  "Hilden",
  "Hildesheim",
  "Hof",
  "Hofheim am Taunus",
  "Homburg",
  "Hoyerswerda",
  "Hückelhoven",
  "Hürth",
  "Ibbenbüren",
  "Ilmenau",
  "Ingolstadt",
  "Ingelheim am Rhein",
  "Iserlohn",
  "Itzehoe",
  "Jena",
  "Jülich",
  "Kaarst",
  "Kaiserslautern",
  "Kamen",
  "Kamp-Lintfort",
  "Kapfenberg",
  "Karlsruhe",
  "Kassel",
  "Kaufbeuren",
  "Kehl",
  "Kempen",
  "Kempten (Allgäu)",
  "Kerpen",
  "Kiel",
  "Kirchheim unter Teck",
  "Kleve",
  "Koblenz",
  "Konstanz",
  "Kornwestheim",
  "Korschenbroich",
  "Krefeld",
  "Kreuztal",
  "Königswinter",
  "Königs Wusterhausen",
  "Köln",
  "Laatzen",
  "Lage",
  "Lahr/Schwarzwald",
  "Lampertheim",
  "Landau in der Pfalz",
  "Langen",
  "Langenfeld",
  "Langenhagen",
  "Landshut",
  "Leer",
  "Lehrte",
  "Leinfelden-Echterdingen",
  "Leipzig",
  "Lemgo",
  "Leonberg",
  "Leverkusen",
  "Limburg an der Lahn",
  "Lingen",
  "Lippstadt",
  "Lohmar",
  "Ludwigsburg",
  "Ludwigshafen am Rhein",
  "Lutherstadt Wittenberg",
  "Lübeck",
  "Lüdenscheid",
  "Lünen",
  "Lüneburg",
  "Löhne",
  "Lörrach",
  "Magdeburg",
  "Maintal",
  "Mainz",
  "Mannheim",
  "Marburg",
  "Marl",
  "Meerbusch",
  "Melle",
  "Memmingen",
  "Menden (Sauerland)",
  "Meppen",
  "Merseburg",
  "Merzig",
  "Mettmann",
  "Minden",
  "Moers",
  "Monheim am Rhein",
  "Mörfelden-Walldorf",
  "München",
  "Münster",
  "Mönchengladbach",
  "Mülheim an der Ruhr",
  "Mühlhausen/Thüringen",
  "Naumburg",
  "Neubrandenburg",
  "Neu-Isenburg",
  "Neumünster",
  "Neuburg an der Donau",
  "Neumarkt in der Oberpfalz",
  "Neunkirchen",
  "Neuruppin",
  "Neuss",
  "Neustadt am Rübenberge",
  "Neustadt an der Weinstraße",
  "Neu-Ulm",
  "Neuwied",
  "Nettetal",
  "Niederkassel",
  "Nienburg/Weser",
  "Norderstedt",
  "Nordhorn",
  "Nordhausen",
  "Nürnberg",
  "Nürtingen",
  "Oberhausen",
  "Oberursel (Taunus)",
  "Oer-Erkenschwick",
  "Offenbach am Main",
  "Offenburg",
  "Oldenburg",
  "Oranienburg",
  "Osnabrück",
  "Osterholz-Scharmbeck",
  "Ostfildern",
  "Paderborn",
  "Papenburg",
  "Passau",
  "Peine",
  "Pforzheim",
  "Pinneberg",
  "Pirmasens",
  "Pirna",
  "Plauen",
  "Porta Westfalica",
  "Potsdam",
  "Pulheim",
  "Radebeul",
  "Radolfzell am Bodensee",
  "Rastatt",
  "Ratingen",
  "Ravensburg",
  "Recklinghausen",
  "Regensburg",
  "Remscheid",
  "Rendsburg",
  "Reutlingen",
  "Rheda-Wiedenbrück",
  "Rheinfelden (Baden)",
  "Rheinberg",
  "Rheine",
  "Rietberg",
  "Rodgau",
  "Rosenheim",
  "Rostock",
  "Rottenburg am Neckar",
  "Rüsselsheim am Main",
  "Saarbrücken",
  "Saarlouis",
  "Salzgitter",
  "Sankt Augustin",
  "Schaffhausen",
  "Schwabach",
  "Schwandorf",
  "Schwerin",
  "Schwerte",
  "Schwäbisch Gmünd",
  "Schwäbisch Hall",
  "Schwedt/Oder",
  "Schweinfurt",
  "Schönebeck",
  "Schorndorf",
  "Seelze",
  "Siegen",
  "Siegburg",
  "Sindelfingen",
  "Singen (Hohentwiel)",
  "Sinsheim",
  "Soest",
  "Solingen",
  "Speyer",
  "St. Ingbert",
  "Stade",
  "Steinfurt",
  "Stendal",
  "Stolberg",
  "Stralsund",
  "Straubing",
  "Stuttgart",
  "Suhl",
  "Taunusstein",
  "Trier",
  "Troisdorf",
  "Tuttlingen",
  "Tübingen",
  "Ulm",
  "Unna",
  "Unterschleißheim",
  "Uelzen",
  "Vechta",
  "Velbert",
  "Viernheim",
  "Viersen",
  "Villingen-Schwenningen",
  "Voerde",
  "Völklingen",
  "Waiblingen",
  "Walsrode",
  "Wandsbek",
  "Warendorf",
  "Wattenscheid",
  "Wedel",
  "Weiden in der Oberpfalz",
  "Weil am Rhein",
  "Weimar",
  "Weinheim",
  "Weißenfels",
  "Werl",
  "Wermelskirchen",
  "Wernigerode",
  "Wesel",
  "Wesseling",
  "Wetzlar",
  "Wiesbaden",
  "Wilhelmshaven",
  "Willich",
  "Winsen",
  "Wismar",
  "Witten",
  "Wolfenbüttel",
  "Wolfsburg",
  "Worms",
  "Wunstorf",
  "Wuppertal",
  "Würselen",
  "Würzburg",
  "Zwickau",
  "Zweibrücken",

  // Österreichische Städte (Quelle: Wikidata)
  "Wien",
  "Graz",
  "Linz",
  "Salzburg",
  "Innsbruck",
  "Klagenfurt am Wörthersee",
  "Wels",
  "Villach",
  "St. Pölten",
  "Dornbirn",
  "Wiener Neustadt",
  "Steyr",
  "Feldkirch",
  "Bregenz",
  "Leonding",
  "Klosterneuburg",
  "Baden bei Wien",
  "Krems",
  "Wolfsberg",
  "Leoben",
  "Traun",
  "Lustenau",
  "Amstetten",
  "Hallein",
  "Mödling",

  // Schweizer Städte (Quelle: Wikidata)
  "Zürich",
  "Genf",
  "Basel",
  "Lausanne",
  "Bern",
  "Winterthur",
  "Luzern",
  "St. Gallen",
  "Lugano",
  "Biel/Bienne",
  "Neuenburg",
  "Bellinzona",
  "Thun",
  "Köniz",
  "Chur",
  "Freiburg im Üechtland",
  "La Chaux-de-Fonds",
  "Lancy",
  "Sitten",
  "Uster",
  "Vernier",
  "Zug",
  "Yverdon-les-Bains",
];
